set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports exec_done]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U16 [get_ports exec_done]
set_property PACKAGE_PIN V17 [get_ports rst]

set_property PACKAGE_PIN L1 [get_ports led_add]
set_property PACKAGE_PIN P1 [get_ports led_exec]
set_property PACKAGE_PIN N3 [get_ports led_hb]
set_property PACKAGE_PIN P3 [get_ports led_hlt]
set_property IOSTANDARD LVCMOS33 [get_ports led_add]
set_property IOSTANDARD LVCMOS33 [get_ports led_exec]
set_property IOSTANDARD LVCMOS33 [get_ports led_hb]
set_property IOSTANDARD LVCMOS33 [get_ports led_hlt]
